/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace RelayerV2 {
  export type DstPriceStruct = {
    dstPriceRatio: PromiseOrValue<BigNumberish>;
    dstGasPriceInWei: PromiseOrValue<BigNumberish>;
  };

  export type DstPriceStructOutput = [BigNumber, BigNumber] & {
    dstPriceRatio: BigNumber;
    dstGasPriceInWei: BigNumber;
  };

  export type DstFloorMarginStruct = {
    chainId: PromiseOrValue<BigNumberish>;
    floorMargin: PromiseOrValue<BigNumberish>;
  };

  export type DstFloorMarginStructOutput = [number, BigNumber] & {
    chainId: number;
    floorMargin: BigNumber;
  };

  export type DstMultiplierStruct = {
    chainId: PromiseOrValue<BigNumberish>;
    multiplier: PromiseOrValue<BigNumberish>;
  };

  export type DstMultiplierStructOutput = [number, BigNumber] & {
    chainId: number;
    multiplier: BigNumber;
  };
}

export interface RelayerV2Interface extends utils.Interface {
  functions: {
    "AIRDROP_GAS_LIMIT()": FunctionFragment;
    "approvedAddresses(address)": FunctionFragment;
    "assignJob(uint16,uint16,address,uint256,bytes)": FunctionFragment;
    "dstConfigLookup(uint16,uint16)": FunctionFragment;
    "dstFloorMarginsUSD(uint16)": FunctionFragment;
    "dstMultipliers(uint16)": FunctionFragment;
    "dstPriceLookup(uint16)": FunctionFragment;
    "dstPriceLookupOld(uint16)": FunctionFragment;
    "fpBytes()": FunctionFragment;
    "getFee(uint16,uint16,address,uint256,bytes)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "isApproved(address)": FunctionFragment;
    "mptOverhead()": FunctionFragment;
    "multiplierBps()": FunctionFragment;
    "onUpgrade(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "priceConfigUpdaters(address)": FunctionFragment;
    "priceFeed()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setApprovedAddress(address,bool)": FunctionFragment;
    "setDstConfig(uint16,uint16,uint128,uint64,uint64)": FunctionFragment;
    "setDstFloorMarginsUSD((uint16,uint128)[])": FunctionFragment;
    "setDstPrice(uint16,uint128,uint128)": FunctionFragment;
    "setDstPriceMultipliers((uint16,uint128)[])": FunctionFragment;
    "setPause(bool)": FunctionFragment;
    "setPriceConfigUpdater(address,bool)": FunctionFragment;
    "setPriceFeed(address)": FunctionFragment;
    "setPriceMultiplierBps(uint128)": FunctionFragment;
    "setStargateAddress(address)": FunctionFragment;
    "stargateBridgeAddress()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uln()": FunctionFragment;
    "validateProofBytes()": FunctionFragment;
    "validateTransactionProofV1(uint16,address,uint256,bytes32,bytes32,bytes)": FunctionFragment;
    "validateTransactionProofV2(uint16,address,uint256,bytes32,bytes32,bytes,address)": FunctionFragment;
    "withdrawFee(address,uint256)": FunctionFragment;
    "withdrawToken(address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "AIRDROP_GAS_LIMIT"
      | "approvedAddresses"
      | "assignJob"
      | "dstConfigLookup"
      | "dstFloorMarginsUSD"
      | "dstMultipliers"
      | "dstPriceLookup"
      | "dstPriceLookupOld"
      | "fpBytes"
      | "getFee"
      | "initialize"
      | "isApproved"
      | "mptOverhead"
      | "multiplierBps"
      | "onUpgrade"
      | "owner"
      | "paused"
      | "priceConfigUpdaters"
      | "priceFeed"
      | "renounceOwnership"
      | "setApprovedAddress"
      | "setDstConfig"
      | "setDstFloorMarginsUSD"
      | "setDstPrice"
      | "setDstPriceMultipliers"
      | "setPause"
      | "setPriceConfigUpdater"
      | "setPriceFeed"
      | "setPriceMultiplierBps"
      | "setStargateAddress"
      | "stargateBridgeAddress"
      | "transferOwnership"
      | "uln"
      | "validateProofBytes"
      | "validateTransactionProofV1"
      | "validateTransactionProofV2"
      | "withdrawFee"
      | "withdrawToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AIRDROP_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvedAddresses",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "assignJob",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "dstConfigLookup",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "dstFloorMarginsUSD",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "dstMultipliers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "dstPriceLookup",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "dstPriceLookupOld",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "fpBytes", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mptOverhead",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiplierBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onUpgrade",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceConfigUpdaters",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovedAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDstConfig",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDstFloorMarginsUSD",
    values: [RelayerV2.DstFloorMarginStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setDstPrice",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDstPriceMultipliers",
    values: [RelayerV2.DstMultiplierStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setPause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceConfigUpdater",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceMultiplierBps",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStargateAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "stargateBridgeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "uln", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateProofBytes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransactionProofV1",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransactionProofV2",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "AIRDROP_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dstConfigLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dstFloorMarginsUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dstMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dstPriceLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dstPriceLookupOld",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fpBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mptOverhead",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplierBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onUpgrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceConfigUpdaters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDstConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDstFloorMarginsUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDstPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDstPriceMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceConfigUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceMultiplierBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStargateAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stargateBridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uln", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateProofBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransactionProofV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransactionProofV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;

  events: {
    "ApproveAddress(address,bool)": EventFragment;
    "AssignJob(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SetDstConfig(uint16,uint16,uint128,uint64,uint64)": EventFragment;
    "SetDstPrice(uint16,uint128,uint128)": EventFragment;
    "SetPriceConfigUpdater(address,bool)": EventFragment;
    "ValueTransferFailed(address,uint256)": EventFragment;
    "Withdraw(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ApproveAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssignJob"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDstConfig"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDstPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetPriceConfigUpdater"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValueTransferFailed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface ApproveAddressEventObject {
  addr: string;
  approved: boolean;
}
export type ApproveAddressEvent = TypedEvent<
  [string, boolean],
  ApproveAddressEventObject
>;

export type ApproveAddressEventFilter = TypedEventFilter<ApproveAddressEvent>;

export interface AssignJobEventObject {
  totalFee: BigNumber;
}
export type AssignJobEvent = TypedEvent<[BigNumber], AssignJobEventObject>;

export type AssignJobEventFilter = TypedEventFilter<AssignJobEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SetDstConfigEventObject {
  chainId: number;
  outboundProofType: number;
  dstNativeAmtCap: BigNumber;
  baseGas: BigNumber;
  gasPerByte: BigNumber;
}
export type SetDstConfigEvent = TypedEvent<
  [number, number, BigNumber, BigNumber, BigNumber],
  SetDstConfigEventObject
>;

export type SetDstConfigEventFilter = TypedEventFilter<SetDstConfigEvent>;

export interface SetDstPriceEventObject {
  chainId: number;
  dstPriceRatio: BigNumber;
  dstGasPriceInWei: BigNumber;
}
export type SetDstPriceEvent = TypedEvent<
  [number, BigNumber, BigNumber],
  SetDstPriceEventObject
>;

export type SetDstPriceEventFilter = TypedEventFilter<SetDstPriceEvent>;

export interface SetPriceConfigUpdaterEventObject {
  priceConfigUpdater: string;
  allow: boolean;
}
export type SetPriceConfigUpdaterEvent = TypedEvent<
  [string, boolean],
  SetPriceConfigUpdaterEventObject
>;

export type SetPriceConfigUpdaterEventFilter =
  TypedEventFilter<SetPriceConfigUpdaterEvent>;

export interface ValueTransferFailedEventObject {
  to: string;
  quantity: BigNumber;
}
export type ValueTransferFailedEvent = TypedEvent<
  [string, BigNumber],
  ValueTransferFailedEventObject
>;

export type ValueTransferFailedEventFilter =
  TypedEventFilter<ValueTransferFailedEvent>;

export interface WithdrawEventObject {
  to: string;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface RelayerV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RelayerV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    AIRDROP_GAS_LIMIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    approvedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    assignJob(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    dstConfigLookup(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        dstNativeAmtCap: BigNumber;
        baseGas: BigNumber;
        gasPerByte: BigNumber;
      }
    >;

    dstFloorMarginsUSD(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dstMultipliers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dstPriceLookup(
      _dstChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[RelayerV2.DstPriceStructOutput]>;

    dstPriceLookupOld(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        dstPriceRatio: BigNumber;
        dstGasPriceInWei: BigNumber;
      }
    >;

    fpBytes(overrides?: CallOverrides): Promise<[number]>;

    getFee(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialize(
      _uln: PromiseOrValue<string>,
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isApproved(
      _relayerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mptOverhead(overrides?: CallOverrides): Promise<[number]>;

    multiplierBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    onUpgrade(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    priceConfigUpdaters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    priceFeed(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setApprovedAddress(
      _relayerAddress: PromiseOrValue<string>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDstConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _dstNativeAmtCap: PromiseOrValue<BigNumberish>,
      _baseGas: PromiseOrValue<BigNumberish>,
      _gasPerByte: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDstFloorMarginsUSD(
      _margins: RelayerV2.DstFloorMarginStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDstPrice(
      _chainId: PromiseOrValue<BigNumberish>,
      _dstPriceRatio: PromiseOrValue<BigNumberish>,
      _dstGasPriceInWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDstPriceMultipliers(
      _multipliers: RelayerV2.DstMultiplierStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPause(
      _paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPriceConfigUpdater(
      _priceConfigUpdater: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPriceMultiplierBps(
      _multiplierBps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStargateAddress(
      _stargateAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stargateBridgeAddress(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uln(overrides?: CallOverrides): Promise<[string]>;

    validateProofBytes(overrides?: CallOverrides): Promise<[number]>;

    validateTransactionProofV1(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateTransactionProofV2(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFee(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  AIRDROP_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  approvedAddresses(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  assignJob(
    _dstChainId: PromiseOrValue<BigNumberish>,
    _outboundProofType: PromiseOrValue<BigNumberish>,
    _userApplication: PromiseOrValue<string>,
    _payloadSize: PromiseOrValue<BigNumberish>,
    _adapterParams: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  dstConfigLookup(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      dstNativeAmtCap: BigNumber;
      baseGas: BigNumber;
      gasPerByte: BigNumber;
    }
  >;

  dstFloorMarginsUSD(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  dstMultipliers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  dstPriceLookup(
    _dstChainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<RelayerV2.DstPriceStructOutput>;

  dstPriceLookupOld(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      dstPriceRatio: BigNumber;
      dstGasPriceInWei: BigNumber;
    }
  >;

  fpBytes(overrides?: CallOverrides): Promise<number>;

  getFee(
    _dstChainId: PromiseOrValue<BigNumberish>,
    _outboundProofType: PromiseOrValue<BigNumberish>,
    _userApplication: PromiseOrValue<string>,
    _payloadSize: PromiseOrValue<BigNumberish>,
    _adapterParams: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialize(
    _uln: PromiseOrValue<string>,
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isApproved(
    _relayerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mptOverhead(overrides?: CallOverrides): Promise<number>;

  multiplierBps(overrides?: CallOverrides): Promise<BigNumber>;

  onUpgrade(
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  priceConfigUpdaters(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  priceFeed(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setApprovedAddress(
    _relayerAddress: PromiseOrValue<string>,
    _approve: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDstConfig(
    _chainId: PromiseOrValue<BigNumberish>,
    _outboundProofType: PromiseOrValue<BigNumberish>,
    _dstNativeAmtCap: PromiseOrValue<BigNumberish>,
    _baseGas: PromiseOrValue<BigNumberish>,
    _gasPerByte: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDstFloorMarginsUSD(
    _margins: RelayerV2.DstFloorMarginStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDstPrice(
    _chainId: PromiseOrValue<BigNumberish>,
    _dstPriceRatio: PromiseOrValue<BigNumberish>,
    _dstGasPriceInWei: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDstPriceMultipliers(
    _multipliers: RelayerV2.DstMultiplierStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPause(
    _paused: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPriceConfigUpdater(
    _priceConfigUpdater: PromiseOrValue<string>,
    _allow: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPriceFeed(
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPriceMultiplierBps(
    _multiplierBps: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStargateAddress(
    _stargateAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stargateBridgeAddress(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uln(overrides?: CallOverrides): Promise<string>;

  validateProofBytes(overrides?: CallOverrides): Promise<number>;

  validateTransactionProofV1(
    _srcChainId: PromiseOrValue<BigNumberish>,
    _dstAddress: PromiseOrValue<string>,
    _gasLimit: PromiseOrValue<BigNumberish>,
    _blockHash: PromiseOrValue<BytesLike>,
    _data: PromiseOrValue<BytesLike>,
    _transactionProof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateTransactionProofV2(
    _srcChainId: PromiseOrValue<BigNumberish>,
    _dstAddress: PromiseOrValue<string>,
    _gasLimit: PromiseOrValue<BigNumberish>,
    _blockHash: PromiseOrValue<BytesLike>,
    _data: PromiseOrValue<BytesLike>,
    _transactionProof: PromiseOrValue<BytesLike>,
    _to: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFee(
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawToken(
    _token: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    AIRDROP_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    approvedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    assignJob(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstConfigLookup(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        dstNativeAmtCap: BigNumber;
        baseGas: BigNumber;
        gasPerByte: BigNumber;
      }
    >;

    dstFloorMarginsUSD(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstMultipliers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstPriceLookup(
      _dstChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<RelayerV2.DstPriceStructOutput>;

    dstPriceLookupOld(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        dstPriceRatio: BigNumber;
        dstGasPriceInWei: BigNumber;
      }
    >;

    fpBytes(overrides?: CallOverrides): Promise<number>;

    getFee(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _uln: PromiseOrValue<string>,
      _priceFeed: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isApproved(
      _relayerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mptOverhead(overrides?: CallOverrides): Promise<number>;

    multiplierBps(overrides?: CallOverrides): Promise<BigNumber>;

    onUpgrade(
      _priceFeed: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    priceConfigUpdaters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    priceFeed(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setApprovedAddress(
      _relayerAddress: PromiseOrValue<string>,
      _approve: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDstConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _dstNativeAmtCap: PromiseOrValue<BigNumberish>,
      _baseGas: PromiseOrValue<BigNumberish>,
      _gasPerByte: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDstFloorMarginsUSD(
      _margins: RelayerV2.DstFloorMarginStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setDstPrice(
      _chainId: PromiseOrValue<BigNumberish>,
      _dstPriceRatio: PromiseOrValue<BigNumberish>,
      _dstGasPriceInWei: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDstPriceMultipliers(
      _multipliers: RelayerV2.DstMultiplierStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setPause(
      _paused: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceConfigUpdater(
      _priceConfigUpdater: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceMultiplierBps(
      _multiplierBps: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStargateAddress(
      _stargateAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    stargateBridgeAddress(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    uln(overrides?: CallOverrides): Promise<string>;

    validateProofBytes(overrides?: CallOverrides): Promise<number>;

    validateTransactionProofV1(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    validateTransactionProofV2(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFee(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ApproveAddress(address,bool)"(
      addr?: null,
      approved?: null
    ): ApproveAddressEventFilter;
    ApproveAddress(addr?: null, approved?: null): ApproveAddressEventFilter;

    "AssignJob(uint256)"(totalFee?: null): AssignJobEventFilter;
    AssignJob(totalFee?: null): AssignJobEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "SetDstConfig(uint16,uint16,uint128,uint64,uint64)"(
      chainId?: null,
      outboundProofType?: null,
      dstNativeAmtCap?: null,
      baseGas?: null,
      gasPerByte?: null
    ): SetDstConfigEventFilter;
    SetDstConfig(
      chainId?: null,
      outboundProofType?: null,
      dstNativeAmtCap?: null,
      baseGas?: null,
      gasPerByte?: null
    ): SetDstConfigEventFilter;

    "SetDstPrice(uint16,uint128,uint128)"(
      chainId?: null,
      dstPriceRatio?: null,
      dstGasPriceInWei?: null
    ): SetDstPriceEventFilter;
    SetDstPrice(
      chainId?: null,
      dstPriceRatio?: null,
      dstGasPriceInWei?: null
    ): SetDstPriceEventFilter;

    "SetPriceConfigUpdater(address,bool)"(
      priceConfigUpdater?: null,
      allow?: null
    ): SetPriceConfigUpdaterEventFilter;
    SetPriceConfigUpdater(
      priceConfigUpdater?: null,
      allow?: null
    ): SetPriceConfigUpdaterEventFilter;

    "ValueTransferFailed(address,uint256)"(
      to?: PromiseOrValue<string> | null,
      quantity?: PromiseOrValue<BigNumberish> | null
    ): ValueTransferFailedEventFilter;
    ValueTransferFailed(
      to?: PromiseOrValue<string> | null,
      quantity?: PromiseOrValue<BigNumberish> | null
    ): ValueTransferFailedEventFilter;

    "Withdraw(address,uint256)"(to?: null, amount?: null): WithdrawEventFilter;
    Withdraw(to?: null, amount?: null): WithdrawEventFilter;
  };

  estimateGas: {
    AIRDROP_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    approvedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assignJob(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    dstConfigLookup(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstFloorMarginsUSD(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstMultipliers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstPriceLookup(
      _dstChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dstPriceLookupOld(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fpBytes(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _uln: PromiseOrValue<string>,
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isApproved(
      _relayerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mptOverhead(overrides?: CallOverrides): Promise<BigNumber>;

    multiplierBps(overrides?: CallOverrides): Promise<BigNumber>;

    onUpgrade(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    priceConfigUpdaters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    priceFeed(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setApprovedAddress(
      _relayerAddress: PromiseOrValue<string>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDstConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _dstNativeAmtCap: PromiseOrValue<BigNumberish>,
      _baseGas: PromiseOrValue<BigNumberish>,
      _gasPerByte: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDstFloorMarginsUSD(
      _margins: RelayerV2.DstFloorMarginStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDstPrice(
      _chainId: PromiseOrValue<BigNumberish>,
      _dstPriceRatio: PromiseOrValue<BigNumberish>,
      _dstGasPriceInWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDstPriceMultipliers(
      _multipliers: RelayerV2.DstMultiplierStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPause(
      _paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPriceConfigUpdater(
      _priceConfigUpdater: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPriceMultiplierBps(
      _multiplierBps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStargateAddress(
      _stargateAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stargateBridgeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uln(overrides?: CallOverrides): Promise<BigNumber>;

    validateProofBytes(overrides?: CallOverrides): Promise<BigNumber>;

    validateTransactionProofV1(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateTransactionProofV2(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFee(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    AIRDROP_GAS_LIMIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approvedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assignJob(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    dstConfigLookup(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dstFloorMarginsUSD(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dstMultipliers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dstPriceLookup(
      _dstChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dstPriceLookupOld(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fpBytes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(
      _dstChainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _userApplication: PromiseOrValue<string>,
      _payloadSize: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _uln: PromiseOrValue<string>,
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isApproved(
      _relayerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mptOverhead(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiplierBps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onUpgrade(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceConfigUpdaters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceFeed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setApprovedAddress(
      _relayerAddress: PromiseOrValue<string>,
      _approve: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDstConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _dstNativeAmtCap: PromiseOrValue<BigNumberish>,
      _baseGas: PromiseOrValue<BigNumberish>,
      _gasPerByte: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDstFloorMarginsUSD(
      _margins: RelayerV2.DstFloorMarginStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDstPrice(
      _chainId: PromiseOrValue<BigNumberish>,
      _dstPriceRatio: PromiseOrValue<BigNumberish>,
      _dstGasPriceInWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDstPriceMultipliers(
      _multipliers: RelayerV2.DstMultiplierStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPause(
      _paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPriceConfigUpdater(
      _priceConfigUpdater: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPriceMultiplierBps(
      _multiplierBps: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStargateAddress(
      _stargateAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stargateBridgeAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uln(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validateProofBytes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateTransactionProofV1(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateTransactionProofV2(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _blockHash: PromiseOrValue<BytesLike>,
      _data: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFee(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawToken(
      _token: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
