/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace UltraLightNode {
  export type ApplicationConfigurationStruct = {
    inboundProofLibraryVersion: PromiseOrValue<BigNumberish>;
    inboundBlockConfirmations: PromiseOrValue<BigNumberish>;
    relayer: PromiseOrValue<string>;
    outboundProofType: PromiseOrValue<BigNumberish>;
    outboundBlockConfirmations: PromiseOrValue<BigNumberish>;
    oracle: PromiseOrValue<string>;
  };

  export type ApplicationConfigurationStructOutput = [
    number,
    BigNumber,
    string,
    number,
    BigNumber,
    string
  ] & {
    inboundProofLibraryVersion: number;
    inboundBlockConfirmations: BigNumber;
    relayer: string;
    outboundProofType: number;
    outboundBlockConfirmations: BigNumber;
    oracle: string;
  };

  export type BlockDataStruct = {
    confirmations: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
  };

  export type BlockDataStructOutput = [BigNumber, string] & {
    confirmations: BigNumber;
    data: string;
  };
}

export interface UltraLightNodeInterface extends utils.Interface {
  functions: {
    "BP_DENOMINATOR()": FunctionFragment;
    "CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS()": FunctionFragment;
    "CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION()": FunctionFragment;
    "CONFIG_TYPE_ORACLE()": FunctionFragment;
    "CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS()": FunctionFragment;
    "CONFIG_TYPE_OUTBOUND_PROOF_TYPE()": FunctionFragment;
    "CONFIG_TYPE_RELAYER()": FunctionFragment;
    "WITHDRAW_TYPE_ORACLE_QUOTED_FEES()": FunctionFragment;
    "WITHDRAW_TYPE_RELAYER_QUOTED_FEES()": FunctionFragment;
    "WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES()": FunctionFragment;
    "addInboundProofLibraryForChain(uint16,address)": FunctionFragment;
    "appConfig(address,uint16)": FunctionFragment;
    "chainAddressSizeMap(uint16)": FunctionFragment;
    "defaultAdapterParams(uint16,uint16)": FunctionFragment;
    "defaultAppConfig(uint16)": FunctionFragment;
    "enableSupportedOutboundProof(uint16,uint16)": FunctionFragment;
    "endpoint()": FunctionFragment;
    "estimateFees(uint16,address,bytes,bool,bytes)": FunctionFragment;
    "getAppConfig(uint16,address)": FunctionFragment;
    "getBlockHeaderData(address,uint16,bytes32)": FunctionFragment;
    "getConfig(uint16,address,uint256)": FunctionFragment;
    "hashLookup(address,uint16,bytes32)": FunctionFragment;
    "inboundProofLibrary(uint16,uint16)": FunctionFragment;
    "layerZeroToken()": FunctionFragment;
    "maxInboundProofLibrary(uint16)": FunctionFragment;
    "oracleQuotedAmount(address)": FunctionFragment;
    "oracleQuotedFees(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "relayerQuotedAmount(address)": FunctionFragment;
    "relayerQuotedFees(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "send(address,uint64,uint16,bytes,bytes,address,address,bytes)": FunctionFragment;
    "setChainAddressSize(uint16,uint256)": FunctionFragment;
    "setConfig(uint16,address,uint256,bytes)": FunctionFragment;
    "setDefaultAdapterParamsForChainId(uint16,uint16,bytes)": FunctionFragment;
    "setDefaultConfigForChainId(uint16,uint16,uint64,address,uint16,uint16,address)": FunctionFragment;
    "setLayerZeroToken(address)": FunctionFragment;
    "setRemoteUln(uint16,bytes32)": FunctionFragment;
    "setTreasury(address)": FunctionFragment;
    "supportedOutboundProof(uint16,uint16)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasuryContract()": FunctionFragment;
    "treasuryNativeFees()": FunctionFragment;
    "treasuryZROFees()": FunctionFragment;
    "ulnLookup(uint16)": FunctionFragment;
    "updateHash(uint16,bytes32,uint256,bytes32)": FunctionFragment;
    "validateTransactionProof(uint16,address,uint256,bytes32,bytes)": FunctionFragment;
    "withdrawNative(uint8,address,address,uint256)": FunctionFragment;
    "withdrawZRO(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BP_DENOMINATOR"
      | "CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS"
      | "CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION"
      | "CONFIG_TYPE_ORACLE"
      | "CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS"
      | "CONFIG_TYPE_OUTBOUND_PROOF_TYPE"
      | "CONFIG_TYPE_RELAYER"
      | "WITHDRAW_TYPE_ORACLE_QUOTED_FEES"
      | "WITHDRAW_TYPE_RELAYER_QUOTED_FEES"
      | "WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES"
      | "addInboundProofLibraryForChain"
      | "appConfig"
      | "chainAddressSizeMap"
      | "defaultAdapterParams"
      | "defaultAppConfig"
      | "enableSupportedOutboundProof"
      | "endpoint"
      | "estimateFees"
      | "getAppConfig"
      | "getBlockHeaderData"
      | "getConfig"
      | "hashLookup"
      | "inboundProofLibrary"
      | "layerZeroToken"
      | "maxInboundProofLibrary"
      | "oracleQuotedAmount"
      | "oracleQuotedFees"
      | "owner"
      | "relayerQuotedAmount"
      | "relayerQuotedFees"
      | "renounceOwnership"
      | "send"
      | "setChainAddressSize"
      | "setConfig"
      | "setDefaultAdapterParamsForChainId"
      | "setDefaultConfigForChainId"
      | "setLayerZeroToken"
      | "setRemoteUln"
      | "setTreasury"
      | "supportedOutboundProof"
      | "transferOwnership"
      | "treasuryContract"
      | "treasuryNativeFees"
      | "treasuryZROFees"
      | "ulnLookup"
      | "updateHash"
      | "validateTransactionProof"
      | "withdrawNative"
      | "withdrawZRO"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BP_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_ORACLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_OUTBOUND_PROOF_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFIG_TYPE_RELAYER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_TYPE_ORACLE_QUOTED_FEES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_TYPE_RELAYER_QUOTED_FEES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addInboundProofLibraryForChain",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "appConfig",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "chainAddressSizeMap",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdapterParams",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAppConfig",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableSupportedOutboundProof",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "endpoint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateFees",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppConfig",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockHeaderData",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfig",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashLookup",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "inboundProofLibrary",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "layerZeroToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxInboundProofLibrary",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleQuotedAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleQuotedFees",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayerQuotedAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "relayerQuotedFees",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainAddressSize",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultAdapterParamsForChainId",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultConfigForChainId",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setLayerZeroToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRemoteUln",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedOutboundProof",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryNativeFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryZROFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ulnLookup",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHash",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransactionProof",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawZRO",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "BP_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_ORACLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_OUTBOUND_PROOF_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFIG_TYPE_RELAYER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_TYPE_ORACLE_QUOTED_FEES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_TYPE_RELAYER_QUOTED_FEES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addInboundProofLibraryForChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainAddressSizeMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdapterParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAppConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableSupportedOutboundProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endpoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockHeaderData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashLookup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inboundProofLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layerZeroToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxInboundProofLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleQuotedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleQuotedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayerQuotedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerQuotedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChainAddressSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultAdapterParamsForChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultConfigForChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLayerZeroToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRemoteUln",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedOutboundProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryNativeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryZROFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ulnLookup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateTransactionProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawZRO",
    data: BytesLike
  ): Result;

  events: {
    "AddInboundProofLibraryForChain(uint16,address)": EventFragment;
    "AppConfigUpdated(address,uint256,bytes)": EventFragment;
    "EnableSupportedOutboundProof(uint16,uint16)": EventFragment;
    "HashReceived(uint16,address,uint256,bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Packet(uint16,bytes)": EventFragment;
    "RelayerParams(uint16,uint64,uint16,bytes)": EventFragment;
    "SetChainAddressSize(uint16,uint256)": EventFragment;
    "SetDefaultAdapterParamsForChainId(uint16,uint16,bytes)": EventFragment;
    "SetDefaultConfigForChainId(uint16,uint16,uint64,address,uint16,uint16,address)": EventFragment;
    "SetLayerZeroToken(address)": EventFragment;
    "SetRelayerFeeContract(address)": EventFragment;
    "SetRemoteUln(uint16,bytes32)": EventFragment;
    "SetTreasury(address)": EventFragment;
    "WithdrawNative(uint8,address,address,address,uint256)": EventFragment;
    "WithdrawZRO(address,address,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AddInboundProofLibraryForChain"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AppConfigUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "EnableSupportedOutboundProof"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HashReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Packet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerParams"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetChainAddressSize"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SetDefaultAdapterParamsForChainId"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDefaultConfigForChainId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetLayerZeroToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetRelayerFeeContract"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetRemoteUln"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTreasury"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawNative"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawZRO"): EventFragment;
}

export interface AddInboundProofLibraryForChainEventObject {
  chainId: number;
  lib: string;
}
export type AddInboundProofLibraryForChainEvent = TypedEvent<
  [number, string],
  AddInboundProofLibraryForChainEventObject
>;

export type AddInboundProofLibraryForChainEventFilter =
  TypedEventFilter<AddInboundProofLibraryForChainEvent>;

export interface AppConfigUpdatedEventObject {
  userApplication: string;
  configType: BigNumber;
  newConfig: string;
}
export type AppConfigUpdatedEvent = TypedEvent<
  [string, BigNumber, string],
  AppConfigUpdatedEventObject
>;

export type AppConfigUpdatedEventFilter =
  TypedEventFilter<AppConfigUpdatedEvent>;

export interface EnableSupportedOutboundProofEventObject {
  chainId: number;
  proofType: number;
}
export type EnableSupportedOutboundProofEvent = TypedEvent<
  [number, number],
  EnableSupportedOutboundProofEventObject
>;

export type EnableSupportedOutboundProofEventFilter =
  TypedEventFilter<EnableSupportedOutboundProofEvent>;

export interface HashReceivedEventObject {
  srcChainId: number;
  oracle: string;
  confirmations: BigNumber;
  blockhash: string;
}
export type HashReceivedEvent = TypedEvent<
  [number, string, BigNumber, string],
  HashReceivedEventObject
>;

export type HashReceivedEventFilter = TypedEventFilter<HashReceivedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PacketEventObject {
  chainId: number;
  payload: string;
}
export type PacketEvent = TypedEvent<[number, string], PacketEventObject>;

export type PacketEventFilter = TypedEventFilter<PacketEvent>;

export interface RelayerParamsEventObject {
  chainId: number;
  nonce: BigNumber;
  outboundProofType: number;
  adapterParams: string;
}
export type RelayerParamsEvent = TypedEvent<
  [number, BigNumber, number, string],
  RelayerParamsEventObject
>;

export type RelayerParamsEventFilter = TypedEventFilter<RelayerParamsEvent>;

export interface SetChainAddressSizeEventObject {
  chainId: number;
  size: BigNumber;
}
export type SetChainAddressSizeEvent = TypedEvent<
  [number, BigNumber],
  SetChainAddressSizeEventObject
>;

export type SetChainAddressSizeEventFilter =
  TypedEventFilter<SetChainAddressSizeEvent>;

export interface SetDefaultAdapterParamsForChainIdEventObject {
  chainId: number;
  proofType: number;
  adapterParams: string;
}
export type SetDefaultAdapterParamsForChainIdEvent = TypedEvent<
  [number, number, string],
  SetDefaultAdapterParamsForChainIdEventObject
>;

export type SetDefaultAdapterParamsForChainIdEventFilter =
  TypedEventFilter<SetDefaultAdapterParamsForChainIdEvent>;

export interface SetDefaultConfigForChainIdEventObject {
  chainId: number;
  inboundProofLib: number;
  inboundBlockConfirm: BigNumber;
  relayer: string;
  outboundProofType: number;
  outboundBlockConfirm: number;
  oracle: string;
}
export type SetDefaultConfigForChainIdEvent = TypedEvent<
  [number, number, BigNumber, string, number, number, string],
  SetDefaultConfigForChainIdEventObject
>;

export type SetDefaultConfigForChainIdEventFilter =
  TypedEventFilter<SetDefaultConfigForChainIdEvent>;

export interface SetLayerZeroTokenEventObject {
  tokenAddress: string;
}
export type SetLayerZeroTokenEvent = TypedEvent<
  [string],
  SetLayerZeroTokenEventObject
>;

export type SetLayerZeroTokenEventFilter =
  TypedEventFilter<SetLayerZeroTokenEvent>;

export interface SetRelayerFeeContractEventObject {
  relayerFeeContract: string;
}
export type SetRelayerFeeContractEvent = TypedEvent<
  [string],
  SetRelayerFeeContractEventObject
>;

export type SetRelayerFeeContractEventFilter =
  TypedEventFilter<SetRelayerFeeContractEvent>;

export interface SetRemoteUlnEventObject {
  chainId: number;
  uln: string;
}
export type SetRemoteUlnEvent = TypedEvent<
  [number, string],
  SetRemoteUlnEventObject
>;

export type SetRemoteUlnEventFilter = TypedEventFilter<SetRemoteUlnEvent>;

export interface SetTreasuryEventObject {
  treasuryAddress: string;
}
export type SetTreasuryEvent = TypedEvent<[string], SetTreasuryEventObject>;

export type SetTreasuryEventFilter = TypedEventFilter<SetTreasuryEvent>;

export interface WithdrawNativeEventObject {
  _type: number;
  _owner: string;
  _msgSender: string;
  _to: string;
  _amount: BigNumber;
}
export type WithdrawNativeEvent = TypedEvent<
  [number, string, string, string, BigNumber],
  WithdrawNativeEventObject
>;

export type WithdrawNativeEventFilter = TypedEventFilter<WithdrawNativeEvent>;

export interface WithdrawZROEventObject {
  _msgSender: string;
  _to: string;
  _amount: BigNumber;
}
export type WithdrawZROEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrawZROEventObject
>;

export type WithdrawZROEventFilter = TypedEventFilter<WithdrawZROEvent>;

export interface UltraLightNode extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UltraLightNodeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BP_DENOMINATOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    CONFIG_TYPE_ORACLE(overrides?: CallOverrides): Promise<[BigNumber]>;

    CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    CONFIG_TYPE_OUTBOUND_PROOF_TYPE(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    CONFIG_TYPE_RELAYER(overrides?: CallOverrides): Promise<[BigNumber]>;

    WITHDRAW_TYPE_ORACLE_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<[number]>;

    WITHDRAW_TYPE_RELAYER_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<[number]>;

    WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES(
      overrides?: CallOverrides
    ): Promise<[number]>;

    addInboundProofLibraryForChain(
      _chainId: PromiseOrValue<BigNumberish>,
      _library: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    appConfig(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, string, number, BigNumber, string] & {
        inboundProofLibraryVersion: number;
        inboundBlockConfirmations: BigNumber;
        relayer: string;
        outboundProofType: number;
        outboundBlockConfirmations: BigNumber;
        oracle: string;
      }
    >;

    chainAddressSizeMap(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    defaultAdapterParams(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    defaultAppConfig(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, string, number, BigNumber, string] & {
        inboundProofLibraryVersion: number;
        inboundBlockConfirmations: BigNumber;
        relayer: string;
        outboundProofType: number;
        outboundBlockConfirmations: BigNumber;
        oracle: string;
      }
    >;

    enableSupportedOutboundProof(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    endpoint(overrides?: CallOverrides): Promise<[string]>;

    estimateFees(
      _chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _payload: PromiseOrValue<BytesLike>,
      _payInZRO: PromiseOrValue<boolean>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { nativeFee: BigNumber; zroFee: BigNumber }
    >;

    getAppConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[UltraLightNode.ApplicationConfigurationStructOutput]>;

    getBlockHeaderData(
      _oracle: PromiseOrValue<string>,
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [UltraLightNode.BlockDataStructOutput] & {
        blockData: UltraLightNode.BlockDataStructOutput;
      }
    >;

    getConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hashLookup(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { confirmations: BigNumber; data: string }
    >;

    inboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    layerZeroToken(overrides?: CallOverrides): Promise<[string]>;

    maxInboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    oracleQuotedAmount(
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    oracleQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    relayerQuotedAmount(
      _relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    relayerQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    send(
      _ua: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      _chainId: PromiseOrValue<BigNumberish>,
      _destination: PromiseOrValue<BytesLike>,
      _payload: PromiseOrValue<BytesLike>,
      _refundAddress: PromiseOrValue<string>,
      _zroPaymentAddress: PromiseOrValue<string>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setChainAddressSize(
      _chainId: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setConfig(
      chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      _config: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDefaultAdapterParamsForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDefaultConfigForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _inboundProofLibraryVersion: PromiseOrValue<BigNumberish>,
      _inboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _relayer: PromiseOrValue<string>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _outboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLayerZeroToken(
      _layerZeroToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRemoteUln(
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _remoteUln: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportedOutboundProof(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasuryContract(overrides?: CallOverrides): Promise<[string]>;

    treasuryNativeFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    treasuryZROFees(overrides?: CallOverrides): Promise<[BigNumber]>;

    ulnLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    updateHash(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _confirmations: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validateTransactionProof(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawNative(
      _type: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawZRO(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BP_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

  CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  CONFIG_TYPE_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

  CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  CONFIG_TYPE_OUTBOUND_PROOF_TYPE(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  CONFIG_TYPE_RELAYER(overrides?: CallOverrides): Promise<BigNumber>;

  WITHDRAW_TYPE_ORACLE_QUOTED_FEES(overrides?: CallOverrides): Promise<number>;

  WITHDRAW_TYPE_RELAYER_QUOTED_FEES(overrides?: CallOverrides): Promise<number>;

  WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES(
    overrides?: CallOverrides
  ): Promise<number>;

  addInboundProofLibraryForChain(
    _chainId: PromiseOrValue<BigNumberish>,
    _library: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  appConfig(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, string, number, BigNumber, string] & {
      inboundProofLibraryVersion: number;
      inboundBlockConfirmations: BigNumber;
      relayer: string;
      outboundProofType: number;
      outboundBlockConfirmations: BigNumber;
      oracle: string;
    }
  >;

  chainAddressSizeMap(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  defaultAdapterParams(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  defaultAppConfig(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, string, number, BigNumber, string] & {
      inboundProofLibraryVersion: number;
      inboundBlockConfirmations: BigNumber;
      relayer: string;
      outboundProofType: number;
      outboundBlockConfirmations: BigNumber;
      oracle: string;
    }
  >;

  enableSupportedOutboundProof(
    _chainId: PromiseOrValue<BigNumberish>,
    _proofType: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  endpoint(overrides?: CallOverrides): Promise<string>;

  estimateFees(
    _chainId: PromiseOrValue<BigNumberish>,
    _ua: PromiseOrValue<string>,
    _payload: PromiseOrValue<BytesLike>,
    _payInZRO: PromiseOrValue<boolean>,
    _adapterParams: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { nativeFee: BigNumber; zroFee: BigNumber }
  >;

  getAppConfig(
    _chainId: PromiseOrValue<BigNumberish>,
    userApplicationAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<UltraLightNode.ApplicationConfigurationStructOutput>;

  getBlockHeaderData(
    _oracle: PromiseOrValue<string>,
    _remoteChainId: PromiseOrValue<BigNumberish>,
    _lookupHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<UltraLightNode.BlockDataStructOutput>;

  getConfig(
    _chainId: PromiseOrValue<BigNumberish>,
    userApplicationAddress: PromiseOrValue<string>,
    _configType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  hashLookup(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { confirmations: BigNumber; data: string }>;

  inboundProofLibrary(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  layerZeroToken(overrides?: CallOverrides): Promise<string>;

  maxInboundProofLibrary(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  oracleQuotedAmount(
    _oracle: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  oracleQuotedFees(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  relayerQuotedAmount(
    _relayer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  relayerQuotedFees(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  send(
    _ua: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    _chainId: PromiseOrValue<BigNumberish>,
    _destination: PromiseOrValue<BytesLike>,
    _payload: PromiseOrValue<BytesLike>,
    _refundAddress: PromiseOrValue<string>,
    _zroPaymentAddress: PromiseOrValue<string>,
    _adapterParams: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setChainAddressSize(
    _chainId: PromiseOrValue<BigNumberish>,
    _size: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setConfig(
    chainId: PromiseOrValue<BigNumberish>,
    _ua: PromiseOrValue<string>,
    _configType: PromiseOrValue<BigNumberish>,
    _config: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDefaultAdapterParamsForChainId(
    _chainId: PromiseOrValue<BigNumberish>,
    _proofType: PromiseOrValue<BigNumberish>,
    _adapterParams: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDefaultConfigForChainId(
    _chainId: PromiseOrValue<BigNumberish>,
    _inboundProofLibraryVersion: PromiseOrValue<BigNumberish>,
    _inboundBlockConfirmations: PromiseOrValue<BigNumberish>,
    _relayer: PromiseOrValue<string>,
    _outboundProofType: PromiseOrValue<BigNumberish>,
    _outboundBlockConfirmations: PromiseOrValue<BigNumberish>,
    _oracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLayerZeroToken(
    _layerZeroToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRemoteUln(
    _remoteChainId: PromiseOrValue<BigNumberish>,
    _remoteUln: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTreasury(
    _treasury: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportedOutboundProof(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasuryContract(overrides?: CallOverrides): Promise<string>;

  treasuryNativeFees(overrides?: CallOverrides): Promise<BigNumber>;

  treasuryZROFees(overrides?: CallOverrides): Promise<BigNumber>;

  ulnLookup(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  updateHash(
    _srcChainId: PromiseOrValue<BigNumberish>,
    _lookupHash: PromiseOrValue<BytesLike>,
    _confirmations: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validateTransactionProof(
    _srcChainId: PromiseOrValue<BigNumberish>,
    _dstAddress: PromiseOrValue<string>,
    _gasLimit: PromiseOrValue<BigNumberish>,
    _lookupHash: PromiseOrValue<BytesLike>,
    _transactionProof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawNative(
    _type: PromiseOrValue<BigNumberish>,
    _owner: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawZRO(
    _to: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BP_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_OUTBOUND_PROOF_TYPE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_RELAYER(overrides?: CallOverrides): Promise<BigNumber>;

    WITHDRAW_TYPE_ORACLE_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<number>;

    WITHDRAW_TYPE_RELAYER_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<number>;

    WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES(
      overrides?: CallOverrides
    ): Promise<number>;

    addInboundProofLibraryForChain(
      _chainId: PromiseOrValue<BigNumberish>,
      _library: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    appConfig(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, string, number, BigNumber, string] & {
        inboundProofLibraryVersion: number;
        inboundBlockConfirmations: BigNumber;
        relayer: string;
        outboundProofType: number;
        outboundBlockConfirmations: BigNumber;
        oracle: string;
      }
    >;

    chainAddressSizeMap(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    defaultAdapterParams(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    defaultAppConfig(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, string, number, BigNumber, string] & {
        inboundProofLibraryVersion: number;
        inboundBlockConfirmations: BigNumber;
        relayer: string;
        outboundProofType: number;
        outboundBlockConfirmations: BigNumber;
        oracle: string;
      }
    >;

    enableSupportedOutboundProof(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    endpoint(overrides?: CallOverrides): Promise<string>;

    estimateFees(
      _chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _payload: PromiseOrValue<BytesLike>,
      _payInZRO: PromiseOrValue<boolean>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { nativeFee: BigNumber; zroFee: BigNumber }
    >;

    getAppConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<UltraLightNode.ApplicationConfigurationStructOutput>;

    getBlockHeaderData(
      _oracle: PromiseOrValue<string>,
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<UltraLightNode.BlockDataStructOutput>;

    getConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    hashLookup(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { confirmations: BigNumber; data: string }
    >;

    inboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    layerZeroToken(overrides?: CallOverrides): Promise<string>;

    maxInboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    oracleQuotedAmount(
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracleQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    relayerQuotedAmount(
      _relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    relayerQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    send(
      _ua: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      _chainId: PromiseOrValue<BigNumberish>,
      _destination: PromiseOrValue<BytesLike>,
      _payload: PromiseOrValue<BytesLike>,
      _refundAddress: PromiseOrValue<string>,
      _zroPaymentAddress: PromiseOrValue<string>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setChainAddressSize(
      _chainId: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setConfig(
      chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      _config: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDefaultAdapterParamsForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDefaultConfigForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _inboundProofLibraryVersion: PromiseOrValue<BigNumberish>,
      _inboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _relayer: PromiseOrValue<string>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _outboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLayerZeroToken(
      _layerZeroToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRemoteUln(
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _remoteUln: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportedOutboundProof(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryContract(overrides?: CallOverrides): Promise<string>;

    treasuryNativeFees(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryZROFees(overrides?: CallOverrides): Promise<BigNumber>;

    ulnLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    updateHash(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _confirmations: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    validateTransactionProof(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawNative(
      _type: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawZRO(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddInboundProofLibraryForChain(uint16,address)"(
      chainId?: null,
      lib?: null
    ): AddInboundProofLibraryForChainEventFilter;
    AddInboundProofLibraryForChain(
      chainId?: null,
      lib?: null
    ): AddInboundProofLibraryForChainEventFilter;

    "AppConfigUpdated(address,uint256,bytes)"(
      userApplication?: null,
      configType?: null,
      newConfig?: null
    ): AppConfigUpdatedEventFilter;
    AppConfigUpdated(
      userApplication?: null,
      configType?: null,
      newConfig?: null
    ): AppConfigUpdatedEventFilter;

    "EnableSupportedOutboundProof(uint16,uint16)"(
      chainId?: null,
      proofType?: null
    ): EnableSupportedOutboundProofEventFilter;
    EnableSupportedOutboundProof(
      chainId?: null,
      proofType?: null
    ): EnableSupportedOutboundProofEventFilter;

    "HashReceived(uint16,address,uint256,bytes32)"(
      srcChainId?: null,
      oracle?: null,
      confirmations?: null,
      blockhash?: null
    ): HashReceivedEventFilter;
    HashReceived(
      srcChainId?: null,
      oracle?: null,
      confirmations?: null,
      blockhash?: null
    ): HashReceivedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Packet(uint16,bytes)"(chainId?: null, payload?: null): PacketEventFilter;
    Packet(chainId?: null, payload?: null): PacketEventFilter;

    "RelayerParams(uint16,uint64,uint16,bytes)"(
      chainId?: null,
      nonce?: null,
      outboundProofType?: null,
      adapterParams?: null
    ): RelayerParamsEventFilter;
    RelayerParams(
      chainId?: null,
      nonce?: null,
      outboundProofType?: null,
      adapterParams?: null
    ): RelayerParamsEventFilter;

    "SetChainAddressSize(uint16,uint256)"(
      chainId?: null,
      size?: null
    ): SetChainAddressSizeEventFilter;
    SetChainAddressSize(
      chainId?: null,
      size?: null
    ): SetChainAddressSizeEventFilter;

    "SetDefaultAdapterParamsForChainId(uint16,uint16,bytes)"(
      chainId?: null,
      proofType?: null,
      adapterParams?: null
    ): SetDefaultAdapterParamsForChainIdEventFilter;
    SetDefaultAdapterParamsForChainId(
      chainId?: null,
      proofType?: null,
      adapterParams?: null
    ): SetDefaultAdapterParamsForChainIdEventFilter;

    "SetDefaultConfigForChainId(uint16,uint16,uint64,address,uint16,uint16,address)"(
      chainId?: null,
      inboundProofLib?: null,
      inboundBlockConfirm?: null,
      relayer?: null,
      outboundProofType?: null,
      outboundBlockConfirm?: null,
      oracle?: null
    ): SetDefaultConfigForChainIdEventFilter;
    SetDefaultConfigForChainId(
      chainId?: null,
      inboundProofLib?: null,
      inboundBlockConfirm?: null,
      relayer?: null,
      outboundProofType?: null,
      outboundBlockConfirm?: null,
      oracle?: null
    ): SetDefaultConfigForChainIdEventFilter;

    "SetLayerZeroToken(address)"(
      tokenAddress?: null
    ): SetLayerZeroTokenEventFilter;
    SetLayerZeroToken(tokenAddress?: null): SetLayerZeroTokenEventFilter;

    "SetRelayerFeeContract(address)"(
      relayerFeeContract?: null
    ): SetRelayerFeeContractEventFilter;
    SetRelayerFeeContract(
      relayerFeeContract?: null
    ): SetRelayerFeeContractEventFilter;

    "SetRemoteUln(uint16,bytes32)"(
      chainId?: null,
      uln?: null
    ): SetRemoteUlnEventFilter;
    SetRemoteUln(chainId?: null, uln?: null): SetRemoteUlnEventFilter;

    "SetTreasury(address)"(treasuryAddress?: null): SetTreasuryEventFilter;
    SetTreasury(treasuryAddress?: null): SetTreasuryEventFilter;

    "WithdrawNative(uint8,address,address,address,uint256)"(
      _type?: null,
      _owner?: null,
      _msgSender?: null,
      _to?: null,
      _amount?: null
    ): WithdrawNativeEventFilter;
    WithdrawNative(
      _type?: null,
      _owner?: null,
      _msgSender?: null,
      _to?: null,
      _amount?: null
    ): WithdrawNativeEventFilter;

    "WithdrawZRO(address,address,uint256)"(
      _msgSender?: null,
      _to?: null,
      _amount?: null
    ): WithdrawZROEventFilter;
    WithdrawZRO(
      _msgSender?: null,
      _to?: null,
      _amount?: null
    ): WithdrawZROEventFilter;
  };

  estimateGas: {
    BP_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_OUTBOUND_PROOF_TYPE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    CONFIG_TYPE_RELAYER(overrides?: CallOverrides): Promise<BigNumber>;

    WITHDRAW_TYPE_ORACLE_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WITHDRAW_TYPE_RELAYER_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addInboundProofLibraryForChain(
      _chainId: PromiseOrValue<BigNumberish>,
      _library: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    appConfig(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainAddressSizeMap(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    defaultAdapterParams(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    defaultAppConfig(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    enableSupportedOutboundProof(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    endpoint(overrides?: CallOverrides): Promise<BigNumber>;

    estimateFees(
      _chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _payload: PromiseOrValue<BytesLike>,
      _payInZRO: PromiseOrValue<boolean>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAppConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBlockHeaderData(
      _oracle: PromiseOrValue<string>,
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashLookup(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    layerZeroToken(overrides?: CallOverrides): Promise<BigNumber>;

    maxInboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracleQuotedAmount(
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracleQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    relayerQuotedAmount(
      _relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    relayerQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    send(
      _ua: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      _chainId: PromiseOrValue<BigNumberish>,
      _destination: PromiseOrValue<BytesLike>,
      _payload: PromiseOrValue<BytesLike>,
      _refundAddress: PromiseOrValue<string>,
      _zroPaymentAddress: PromiseOrValue<string>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setChainAddressSize(
      _chainId: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setConfig(
      chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      _config: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDefaultAdapterParamsForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDefaultConfigForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _inboundProofLibraryVersion: PromiseOrValue<BigNumberish>,
      _inboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _relayer: PromiseOrValue<string>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _outboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLayerZeroToken(
      _layerZeroToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRemoteUln(
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _remoteUln: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportedOutboundProof(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasuryContract(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryNativeFees(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryZROFees(overrides?: CallOverrides): Promise<BigNumber>;

    ulnLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateHash(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _confirmations: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validateTransactionProof(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawNative(
      _type: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawZRO(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BP_DENOMINATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONFIG_TYPE_INBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CONFIG_TYPE_INBOUND_PROOF_LIBRARY_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CONFIG_TYPE_ORACLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CONFIG_TYPE_OUTBOUND_BLOCK_CONFIRMATIONS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CONFIG_TYPE_OUTBOUND_PROOF_TYPE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CONFIG_TYPE_RELAYER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WITHDRAW_TYPE_ORACLE_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WITHDRAW_TYPE_RELAYER_QUOTED_FEES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WITHDRAW_TYPE_TREASURY_PROTOCOL_FEES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addInboundProofLibraryForChain(
      _chainId: PromiseOrValue<BigNumberish>,
      _library: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    appConfig(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainAddressSizeMap(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    defaultAdapterParams(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    defaultAppConfig(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    enableSupportedOutboundProof(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    endpoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    estimateFees(
      _chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _payload: PromiseOrValue<BytesLike>,
      _payInZRO: PromiseOrValue<boolean>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBlockHeaderData(
      _oracle: PromiseOrValue<string>,
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfig(
      _chainId: PromiseOrValue<BigNumberish>,
      userApplicationAddress: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashLookup(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    layerZeroToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxInboundProofLibrary(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracleQuotedAmount(
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracleQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayerQuotedAmount(
      _relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    relayerQuotedFees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    send(
      _ua: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      _chainId: PromiseOrValue<BigNumberish>,
      _destination: PromiseOrValue<BytesLike>,
      _payload: PromiseOrValue<BytesLike>,
      _refundAddress: PromiseOrValue<string>,
      _zroPaymentAddress: PromiseOrValue<string>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setChainAddressSize(
      _chainId: PromiseOrValue<BigNumberish>,
      _size: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setConfig(
      chainId: PromiseOrValue<BigNumberish>,
      _ua: PromiseOrValue<string>,
      _configType: PromiseOrValue<BigNumberish>,
      _config: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultAdapterParamsForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _proofType: PromiseOrValue<BigNumberish>,
      _adapterParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultConfigForChainId(
      _chainId: PromiseOrValue<BigNumberish>,
      _inboundProofLibraryVersion: PromiseOrValue<BigNumberish>,
      _inboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _relayer: PromiseOrValue<string>,
      _outboundProofType: PromiseOrValue<BigNumberish>,
      _outboundBlockConfirmations: PromiseOrValue<BigNumberish>,
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLayerZeroToken(
      _layerZeroToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRemoteUln(
      _remoteChainId: PromiseOrValue<BigNumberish>,
      _remoteUln: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportedOutboundProof(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasuryContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasuryNativeFees(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    treasuryZROFees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ulnLookup(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateHash(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _confirmations: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validateTransactionProof(
      _srcChainId: PromiseOrValue<BigNumberish>,
      _dstAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _lookupHash: PromiseOrValue<BytesLike>,
      _transactionProof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawNative(
      _type: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawZRO(
      _to: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
